---
kind: "operation"
client: "rug-cli 0.22.0"
editor:
  name: "atomist-rugs.rug-editors.ConvertExistingProjectToRugArchiveWithGenerator"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.8.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "b29e16a2eb08430790d6ef7d72ab2c199786d7c0"
    sha: "b29e16a"
  parameters:
    - "rug_archive_name": "rug-language-extension"
    - "rug_archive_group_id": "atomist-rugs"
    - "description": "Generator for Rug language extensions"
    - "generator_name": "NewRugLanguageExtensionProject"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScript"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.8.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "b29e16a2eb08430790d6ef7d72ab2c199786d7c0"
    sha: "b29e16a"
  parameters:
    - "rug_version": "0.12.0"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "AddTypeScriptGenerator"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.9.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "82acbef9ce2c04e0cb6316b9fde702a89469a85b"
    sha: "82acbef"
  parameters:
    - "generator_name": "NewRugLanguageExtensionProject"
    - "description": "create a new Scala Rug language extension project"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.13.0"
  origin:
    repo: "https://github.com/atomist-rugs/travis-editors.git"
    branch: "5899fd260998d6eb2b6780758d51356ba71b01d4"
    sha: "5899fd2"
  parameters:
    - "repo_slug": "atomist-rugs/rug-language-extension"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

