dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: iXds/gmyxbsvZrAIVhUe8n2nfFWcbuw9uEdjjI1CBxuGIYUevZl+278GbC+69Pci9ctqF2byL3HQVeCS53uRMsI7lBbG3DfoYkcZFQlz34KAF0z0LLgx05kayphq4WEaawIOZBx7QgbMBhm9M/qawH7u/dxSXk7HbARe2gr65X4YsBPJq9YdCgi6BPkC6n93AnwHLxJWIblHFF08fonXlygFu2GwJtyPXWWgozIIf55hVJIouCjaAuzy9wPhuPDuJo/CPdm44sg1H5NesFmYnLkj2P6qY8RWm4OZxUUcYiRKoYLhM8xrS1ngXUPv8Cs6zQRA9VzwzzHtDr50C18Eq7xQdVwBYoo/+cE+5L3D585DVxLrrY7dcoODVjGBk6kMUaehRZN9u3mxAkd625IFSYNCTdW1OMuGZKaDHBFpxHdsO0gzOvwYuVzk6EJttrCO9ka/ArSpFSBftXCmVPaPtaJfI6jpyRO7JLI5OvLRxnfZPaVehZcHPDrOLZy+qSKldB9A744WFQnDvfVXkvmA/lZtzyl/3utzz1oZ/Ji/eHpd3j1ofiDwR1jV7s9MSAcFmmhi1KvoRnlSeUUOPBPAFJXTWmH6tjJOw2H61DU7ySIMNKikgwHCaeA0gWRovKDaND+BAW7ldp9YL5YTEniVnhzeaMIamxYEm2fHBDa+jQA=
  - secure: M/a2+Mo6C0DIhJX9QbUWnapmBO5UjbwdzhHjkArUz/qkB3B1bNhLwOJ7c18M0EWFlLxBZNWnOWwhbywUljZQs0O+1U7KevUPAzWk4wN0FnzEJZzIS0izM/+VlWwaIOvWth5MSGuqY3j03rZFT+BxQaxo0p8si+b7QPrLjLmUVNs8tyBpmtiGeglimjfAyRaB1W0Uvk71vFjhBMR/LYI1Ko5nq4tmfOwM8Ne9OEA7Vk5wQaba4HuNpHbgVuYzN4T5iRCxp3rF0sfN7ZgJEko3lduJ4BBYhMr+VMAUHi3MFMg4hbytyJGMsaoEkKocjSNktQ+UTnREOPJj1HBoKSBtJZsH6YbAyIaOzbYmThsVZunoRSDEVa39yPQJHpmb/1kfsuNK7HkI3UfjqFP9WoE7qdUb1QeZJxysx66+IkbzGGbnVgg6OBnhaHGfS0bFf9ioEOZeAsVuiB1++MguzKymerQPzMILAyB10ZsnqKjq7c7PxHE/kAzJPYmLdwzjfcqd83e0AvOq2Fr+5vdbwV4FOho6G/zzh7KaRspIUCAv16dCIUV1kCjK/3xvHNu4flwM6yqZtZcNlHMpmMg7aFlovaW+GymKHRES5XunpIhhKMBCOHG/8adr32mP1RYrVvd0V2W3V6CvsuQxSAfxlhwMe7gyU1pA/LUWN8u2fu0R/kw=
  - secure: Ngsc3i2A1yI2Uig2eyZYta9WicXDkwjnzv9x43HWzpE3K3JsDkchun0vV9/cxaZjAE0Eewd5aFO9yBdm9WzRBBpnUZ/egqW3+XY6KOnSpk+S2R0Jdw//0FTUTjk7nZHJpmlqaRcqrQ8I0f4hTy716ZfBxBssF1k+9P8I5iFrJ0DqOSmjB5H8P0u00IrN06wm01gpVhSSaPWz/mXCrwGVxJeJkosOA56nDPen31QgyGk8+dCABg/GNJW7o13vJXlma63wtco11QR+EJqXVLPbfk+r1MKdxsiaIeK6TkSp19XLWWkgTv8EihZsjcbF3eVSMVwMDANJ0t1zzDxklY72gYmzuBBjR1R04IqVJJ5tfJKCAop40fh6j9YE8PtXYDHWZLVkOsxfKy1iqe0ZEXT67Tiv/M11KQFbz4xpJvqUBCp5Fm18sVgNaaEfBtDSBaYanywlk4Chlg6+vHIuVqwABrWU8UI2Jm3gbBMtLF5yru43jUbGOUQ2bAESOXjfV+8ncswb3dkEKtW6X7mPBBCl3ooJ3rGUjtSQv8gldO+75w54kmxUEWIK1UFsZB3Nk3ZoPZpFnkAQxJ+PM+7N0vTNhDpov0/ALjoAisLJ75PRGnF2KkFDxHixUqgI6dRjCpE0SJGF79/uDnPLqVMoMXNvxJK1aI3UTn6lrm1HifyfJQc=
install:
- nvm install 6.9.2
- npm install -g typescript
script: ./mvnw -B -V install && bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
